# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/)
# Copyright 2024-present Datadog, Inc.
# Copyright 2026 StepSecurity
name: Nightly validation
on:
  workflow_dispatch: # allow manual trigger for on-demand validation

jobs:
  test-install:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, macos-latest-large, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install default version
        uses: ./
        id: install

      - name: Verify install
        shell: bash
        run: |
          datadog-ci version
          [[ "${{ steps.install.outputs.version }}" == v5.* ]]
